//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Experimental/Vive Tracker Input System/New Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""Haptic"",
            ""id"": ""d2d3f7a3-c0e1-4eed-bc10-0766e2527453"",
            ""actions"": [
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""d0da20a4-4c62-4171-80d9-2442198f14e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""24b68f85-9511-443a-9ec2-f681a57dbe05"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Haptic
        m_Haptic = asset.FindActionMap("Haptic", throwIfNotFound: true);
        m_Haptic_Trigger = m_Haptic.FindAction("Trigger", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Haptic
    private readonly InputActionMap m_Haptic;
    private IHapticActions m_HapticActionsCallbackInterface;
    private readonly InputAction m_Haptic_Trigger;
    public struct HapticActions
    {
        private @NewControls m_Wrapper;
        public HapticActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Trigger => m_Wrapper.m_Haptic_Trigger;
        public InputActionMap Get() { return m_Wrapper.m_Haptic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HapticActions set) { return set.Get(); }
        public void SetCallbacks(IHapticActions instance)
        {
            if (m_Wrapper.m_HapticActionsCallbackInterface != null)
            {
                @Trigger.started -= m_Wrapper.m_HapticActionsCallbackInterface.OnTrigger;
                @Trigger.performed -= m_Wrapper.m_HapticActionsCallbackInterface.OnTrigger;
                @Trigger.canceled -= m_Wrapper.m_HapticActionsCallbackInterface.OnTrigger;
            }
            m_Wrapper.m_HapticActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Trigger.started += instance.OnTrigger;
                @Trigger.performed += instance.OnTrigger;
                @Trigger.canceled += instance.OnTrigger;
            }
        }
    }
    public HapticActions @Haptic => new HapticActions(this);
    public interface IHapticActions
    {
        void OnTrigger(InputAction.CallbackContext context);
    }
}
